#include "cpu/cpu.h"

void gb::cpu::SetupInstructionTable()
{
    instructionTable[0x00] = [this] { gb::cpu::NO_OP(); };
    instructionTable[0x01] = [this] { gb::cpu::LD_NN_D16(BC); };
    instructionTable[0x02] = [this] { gb::cpu::LD_XX_Y(BC, &a); };
    instructionTable[0x03] = [this] { gb::cpu::SetComboRegister(BC, gb::cpu::GetComboRegister(BC) + 1); cycles += 8; };
    instructionTable[0x04] = [this] { gb::cpu::INC_X(&b); };
    instructionTable[0x05] = [this] { gb::cpu::DEC_X(&b); };
    instructionTable[0x06] = [this] { gb::cpu::LD_X_D8(&b); };
    instructionTable[0x07] = [this] { gb::cpu::RLCA(); };
    instructionTable[0x08] = [this] { gb::cpu::LD_D16_SP(); };
    instructionTable[0x09] = [this] { gb::cpu::ADD_XX_YY(HL, BC); };
    instructionTable[0x0A] = [this] { gb::cpu::LD_X_YY(&a, GetComboRegister(BC)); };
    instructionTable[0x0B] = [this] { gb::cpu::DEC_XX(BC); };
    instructionTable[0x0C] = [this] { gb::cpu::INC_X(&c); };
    instructionTable[0x0D] = [this] { gb::cpu::DEC_X(&c); };
    instructionTable[0x0E] = [this] { gb::cpu::LD_X_D8(&c); };
    instructionTable[0x0F] = [this] { gb::cpu::RRCA(); };

    instructionTable[0x11] = [this] { gb::cpu::LD_NN_D16(DE); };
    instructionTable[0x12] = [this] { gb::cpu::LD_XX_Y(DE, &a); };
    instructionTable[0x13] = [this] { gb::cpu::SetComboRegister(DE, gb::cpu::GetComboRegister(DE) + 1); cycles += 8; };
    instructionTable[0x14] = [this] { gb::cpu::INC_X(&d); };
    instructionTable[0x15] = [this] { gb::cpu::DEC_X(&d); };
    instructionTable[0x16] = [this] { gb::cpu::LD_X_D8(&d); };
    instructionTable[0x17] = [this] { gb::cpu::RL_X(&a); gb::cpu::ResetFlag(FLAG_Z); };
    instructionTable[0x18] = [this] { gb::cpu::JR_D8(); };
    instructionTable[0x19] = [this] { gb::cpu::ADD_XX_YY(HL, DE); };
    instructionTable[0x1A] = [this] { gb::cpu::LD_X_YY(&a, GetComboRegister(DE)); };
    instructionTable[0x1B] = [this] { gb::cpu::DEC_XX(DE); };
    instructionTable[0x1C] = [this] { gb::cpu::INC_X(&e); };
    instructionTable[0x1D] = [this] { gb::cpu::DEC_X(&e); };
    instructionTable[0x1E] = [this] { gb::cpu::LD_X_D8(&e); };
    instructionTable[0x1F] = [this] { gb::cpu::RRA(); };

    instructionTable[0x20] = [this] { gb::cpu::JR_CC_E(!isFlagSet(FLAG_Z)); };
    instructionTable[0x21] = [this] { gb::cpu::LD_NN_D16(HL); };
    instructionTable[0x22] = [this] { gb::cpu::LD_HL_INC_A(); };
    instructionTable[0x23] = [this] { gb::cpu::SetComboRegister(HL, gb::cpu::GetComboRegister(HL) + 1); cycles += 8; };
    instructionTable[0x24] = [this] { gb::cpu::INC_X(&h); };
    instructionTable[0x25] = [this] { gb::cpu::DEC_X(&h); };
    instructionTable[0x26] = [this] { gb::cpu::LD_X_D8(&h); };
    instructionTable[0x27] = [this] { gb::cpu::DAA(); };
    instructionTable[0x28] = [this] { gb::cpu::JR_CC_E(isFlagSet(FLAG_Z)); };
    instructionTable[0x29] = [this] { gb::cpu::ADD_XX_YY(HL, HL); };
    instructionTable[0x2A] = [this] { gb::cpu::LD_A_HL_INC(); };
    instructionTable[0x2B] = [this] { gb::cpu::DEC_XX(HL); }; 
    instructionTable[0x2C] = [this] { gb::cpu::INC_X(&l); };
    instructionTable[0x2D] = [this] { gb::cpu::DEC_X(&l); };
    instructionTable[0x2E] = [this] { gb::cpu::LD_X_D8(&l); };
    instructionTable[0x2F] = [this] { gb::cpu::CPL(); };

    instructionTable[0x30] = [this] { gb::cpu::JR_CC_E(!isFlagSet(FLAG_C)); };
    instructionTable[0x31] = [this] { gb::cpu::LD_SP_D16(); };
    instructionTable[0x32] = [this] { gb::cpu::LD_HL_DEC_A(); };
    instructionTable[0x33] = [this] { stack_pointer++; cycles += 8; };
    instructionTable[0x34] = [this] { gb::cpu::INC_XX_VAL(HL); };
    instructionTable[0x35] = [this] { gb::cpu::DEC_I_XX(HL); };
    instructionTable[0x36] = [this] { gb::cpu::LD_HL_D8(); };
    instructionTable[0x37] = [this] { gb::cpu::SCF(); };
    instructionTable[0x38] = [this] { gb::cpu::JR_CC_E(isFlagSet(FLAG_C)); };
    instructionTable[0x39] = [this] { gb::cpu::ADD_HL_SP(); };
    instructionTable[0x3A] = [this] { gb::cpu::LD_A_HL_DEC(); };
    instructionTable[0x3B] = [this] { stack_pointer--; cycles += 8; };
    instructionTable[0x3C] = [this] { gb::cpu::INC_X(&a); };
    instructionTable[0x3D] = [this] { gb::cpu::DEC_X(&a); };
    instructionTable[0x3E] = [this] { gb::cpu::LD_X_D8(&a); };
    instructionTable[0x3F] = [this] { gb::cpu::CCF(); };

    instructionTable[0x40] = [this] { gb::cpu::LD_X_Y(&b, b); };
    instructionTable[0x41] = [this] { gb::cpu::LD_X_Y(&b, c); };
    instructionTable[0x42] = [this] { gb::cpu::LD_X_Y(&b, d); };
    instructionTable[0x43] = [this] { gb::cpu::LD_X_Y(&b, e); };
    instructionTable[0x44] = [this] { gb::cpu::LD_X_Y(&b, h); };
    instructionTable[0x45] = [this] { gb::cpu::LD_X_Y(&b, l); };
    instructionTable[0x46] = [this] { gb::cpu::LD_X_DHL(&b); };
    instructionTable[0x47] = [this] { gb::cpu::LD_X_Y(&b, a); };
    instructionTable[0x48] = [this] { gb::cpu::LD_X_Y(&c, b); };
    instructionTable[0x49] = [this] { gb::cpu::LD_X_Y(&c, c); };
    instructionTable[0x4A] = [this] { gb::cpu::LD_X_Y(&c, d); };
    instructionTable[0x4B] = [this] { gb::cpu::LD_X_Y(&c, e); };
    instructionTable[0x4C] = [this] { gb::cpu::LD_X_Y(&c, h); };
    instructionTable[0x4D] = [this] { gb::cpu::LD_X_Y(&c, l); };
    instructionTable[0x4E] = [this] { gb::cpu::LD_X_DHL(&c); };
    instructionTable[0x4F] = [this] { gb::cpu::LD_X_Y(&c, a); };
    
    instructionTable[0x50] = [this] { gb::cpu::LD_X_Y(&d, b); };
    instructionTable[0x51] = [this] { gb::cpu::LD_X_Y(&d, c); };
    instructionTable[0x52] = [this] { gb::cpu::LD_X_Y(&d, d); };
    instructionTable[0x53] = [this] { gb::cpu::LD_X_Y(&d, e); };
    instructionTable[0x54] = [this] { gb::cpu::LD_X_Y(&d, h); };
    instructionTable[0x55] = [this] { gb::cpu::LD_X_Y(&d, l); };
    instructionTable[0x56] = [this] { gb::cpu::LD_X_DHL(&d); };
    instructionTable[0x57] = [this] { gb::cpu::LD_X_Y(&d, a); };
    instructionTable[0x58] = [this] { gb::cpu::LD_X_Y(&e, b); };
    instructionTable[0x59] = [this] { gb::cpu::LD_X_Y(&e, c); };
    instructionTable[0x5A] = [this] { gb::cpu::LD_X_Y(&e, d); };
    instructionTable[0x5B] = [this] { gb::cpu::LD_X_Y(&e, e); };
    instructionTable[0x5C] = [this] { gb::cpu::LD_X_Y(&e, h); };
    instructionTable[0x5D] = [this] { gb::cpu::LD_X_Y(&e, l); };
    instructionTable[0x5E] = [this] { gb::cpu::LD_X_DHL(&e); };
    instructionTable[0x5F] = [this] { gb::cpu::LD_X_Y(&e, a); };

    instructionTable[0x60] = [this] { gb::cpu::LD_X_Y(&h, b); };
    instructionTable[0x61] = [this] { gb::cpu::LD_X_Y(&h, c); };
    instructionTable[0x62] = [this] { gb::cpu::LD_X_Y(&h, d); };
    instructionTable[0x63] = [this] { gb::cpu::LD_X_Y(&h, e); };
    instructionTable[0x64] = [this] { gb::cpu::LD_X_Y(&h, h); };
    instructionTable[0x65] = [this] { gb::cpu::LD_X_Y(&h, l); };
    instructionTable[0x66] = [this] { gb::cpu::LD_X_DHL(&h); };
    instructionTable[0x67] = [this] { gb::cpu::LD_X_Y(&h, a); };
    instructionTable[0x68] = [this] { gb::cpu::LD_X_Y(&l, b); };
    instructionTable[0x69] = [this] { gb::cpu::LD_X_Y(&l, c); };
    instructionTable[0x6A] = [this] { gb::cpu::LD_X_Y(&l, d); };
    instructionTable[0x6B] = [this] { gb::cpu::LD_X_Y(&l, e); };
    instructionTable[0x6C] = [this] { gb::cpu::LD_X_Y(&l, h); };
    instructionTable[0x6D] = [this] { gb::cpu::LD_X_Y(&l, l); };
    instructionTable[0x6E] = [this] { gb::cpu::LD_X_DHL(&l); };
    instructionTable[0x6F] = [this] { gb::cpu::LD_X_Y(&l, a); };

    instructionTable[0x70] = [this] { gb::cpu::LD_HL_X(&b); };
    instructionTable[0x71] = [this] { gb::cpu::LD_HL_X(&c); };
    instructionTable[0x72] = [this] { gb::cpu::LD_HL_X(&d); };
    instructionTable[0x73] = [this] { gb::cpu::LD_HL_X(&e); };
    instructionTable[0x74] = [this] { gb::cpu::LD_HL_X(&h); };
    instructionTable[0x75] = [this] { gb::cpu::LD_HL_X(&l); };
    instructionTable[0x77] = [this] { gb::cpu::LD_HL_X(&a); };
    instructionTable[0x78] = [this] { gb::cpu::LD_X_Y(&a, b); };
    instructionTable[0x79] = [this] { gb::cpu::LD_X_Y(&a, c); };
    instructionTable[0x7A] = [this] { gb::cpu::LD_X_Y(&a, d); };
    instructionTable[0x7B] = [this] { gb::cpu::LD_X_Y(&a, e); };
    instructionTable[0x7C] = [this] { gb::cpu::LD_X_Y(&a, h); };
    instructionTable[0x7D] = [this] { gb::cpu::LD_X_Y(&a, l); };
    instructionTable[0x7E] = [this] { gb::cpu::LD_X_HL(&a); };
    instructionTable[0x7F] = [this] { gb::cpu::LD_X_Y(&a, a); };
    
    instructionTable[0x80] = [this] { gb::cpu::ADD_X(&b); };
    instructionTable[0x81] = [this] { gb::cpu::ADD_X(&c); };
    instructionTable[0x82] = [this] { gb::cpu::ADD_X(&d); };
    instructionTable[0x83] = [this] { gb::cpu::ADD_X(&e); };
    instructionTable[0x84] = [this] { gb::cpu::ADD_X(&h); };
    instructionTable[0x85] = [this] { gb::cpu::ADD_X(&l); };
    instructionTable[0x86] = [this] { gb::cpu::ADD_HL(); };
    instructionTable[0x87] = [this] { gb::cpu::ADD_X(&a); };
    instructionTable[0x88] = [this] { gb::cpu::ADC_X(&b); };
    instructionTable[0x89] = [this] { gb::cpu::ADC_X(&c); };
    instructionTable[0x8A] = [this] { gb::cpu::ADC_X(&d); };
    instructionTable[0x8B] = [this] { gb::cpu::ADC_X(&e); };
    instructionTable[0x8C] = [this] { gb::cpu::ADC_X(&h); };
    instructionTable[0x8D] = [this] { gb::cpu::ADC_X(&l); };
    instructionTable[0x8E] = [this] { gb::cpu::ADC_A_NN(memory->read(GetComboRegister(HL))); };
    instructionTable[0x8F] = [this] { gb::cpu::ADC_X(&a); };

    instructionTable[0x90] = [this] { gb::cpu::SUB_X(b); };
    instructionTable[0x91] = [this] { gb::cpu::SUB_X(c); };
    instructionTable[0x92] = [this] { gb::cpu::SUB_X(d); };
    instructionTable[0x93] = [this] { gb::cpu::SUB_X(e); };
    instructionTable[0x94] = [this] { gb::cpu::SUB_X(h); };
    instructionTable[0x95] = [this] { gb::cpu::SUB_X(l); };
    instructionTable[0x96] = [this] { gb::cpu::SUB_X(memory->read(GetComboRegister(HL))); cycles += 4; };
    instructionTable[0x97] = [this] { gb::cpu::SUB_X(a); };
    instructionTable[0x98] = [this] { gb::cpu::SBC_X(&b); };
    instructionTable[0x99] = [this] { gb::cpu::SBC_X(&c); };
    instructionTable[0x9A] = [this] { gb::cpu::SBC_X(&d); };
    instructionTable[0x9B] = [this] { gb::cpu::SBC_X(&e); };
    instructionTable[0x9C] = [this] { gb::cpu::SBC_X(&h); };
    instructionTable[0x9D] = [this] { gb::cpu::SBC_X(&l); };
    instructionTable[0x9E] = [this] { gb::cpu::SBC_HL(); };
    instructionTable[0x9F] = [this] { gb::cpu::SBC_X(&a); };

    instructionTable[0xA0] = [this] { gb::cpu::AND_X(&b); };
    instructionTable[0xA1] = [this] { gb::cpu::AND_X(&c); };
    instructionTable[0xA2] = [this] { gb::cpu::AND_X(&d); };
    instructionTable[0xA3] = [this] { gb::cpu::AND_X(&e); };
    instructionTable[0xA4] = [this] { gb::cpu::AND_X(&h); };
    instructionTable[0xA5] = [this] { gb::cpu::AND_X(&l); };
    instructionTable[0xA7] = [this] { gb::cpu::AND_X(&a); };
    instructionTable[0xA8] = [this] { gb::cpu::XOR_X(&b); };
    instructionTable[0xA9] = [this] { gb::cpu::XOR_X(&c); };
    instructionTable[0xAA] = [this] { gb::cpu::XOR_X(&d); };
    instructionTable[0xAB] = [this] { gb::cpu::XOR_X(&e); };
    instructionTable[0xAC] = [this] { gb::cpu::XOR_X(&h); };
    instructionTable[0xAD] = [this] { gb::cpu::XOR_X(&l); };
    instructionTable[0xAE] = [this] { gb::cpu::XOR_HL(); };
    instructionTable[0xAF] = [this] { gb::cpu::XOR_X(&a); };

    instructionTable[0xB0] = [this] { gb::cpu::OR_X(&b); };
    instructionTable[0xB1] = [this] { gb::cpu::OR_X(&c); };
    instructionTable[0xB2] = [this] { gb::cpu::OR_X(&d); };
    instructionTable[0xB3] = [this] { gb::cpu::OR_X(&e); };
    instructionTable[0xB4] = [this] { gb::cpu::OR_X(&h); };
    instructionTable[0xB5] = [this] { gb::cpu::OR_X(&l); };
    instructionTable[0xB6] = [this] { gb::cpu::OR_HL(); };
    instructionTable[0xB7] = [this] { gb::cpu::OR_X(&a); };
    instructionTable[0xB8] = [this] { gb::cpu::CP_X(b); };
    instructionTable[0xB9] = [this] { gb::cpu::CP_X(c); };
    instructionTable[0xBA] = [this] { gb::cpu::CP_X(d); };
    instructionTable[0xBB] = [this] { gb::cpu::CP_X(e); };
    instructionTable[0xBC] = [this] { gb::cpu::CP_X(h); };
    instructionTable[0xBD] = [this] { gb::cpu::CP_X(l); };
    instructionTable[0xBE] = [this] { gb::cpu::CP_HL(); };
    instructionTable[0xBF] = [this] { gb::cpu::CP_X(a); };

    instructionTable[0xC0] = [this] { gb::cpu::RET_NZ(); };
    instructionTable[0xC1] = [this] { gb::cpu::POP_XX(BC); };
    instructionTable[0xC2] = [this] { gb::cpu::JP_CC_NN(!isFlagSet(FLAG_Z)); };
    instructionTable[0xC3] = [this] { gb::cpu::JP_A16(); };
    instructionTable[0xC4] = [this] { gb::cpu::CALL_NZ_NN(); };
    instructionTable[0xC5] = [this] { gb::cpu::PUSH_XX(BC); };
    instructionTable[0xC6] = [this] { gb::cpu::ADD_N(); };
    instructionTable[0xC8] = [this] { gb::cpu::RET_Z(); };
    instructionTable[0xC9] = [this] { gb::cpu::RET(); };
    instructionTable[0xCA] = [this] { gb::cpu::JP_CC_NN(isFlagSet(FLAG_Z)); };
    instructionTable[0xCD] = [this] { gb::cpu::CALL_A16(); };
    instructionTable[0xCE] = [this] { gb::cpu::ADC_A_NN(memory->read(program_counter++)); };
    instructionTable[0xCF] = [this] { gb::cpu::RST_XX(0x08); };

    instructionTable[0xD0] = [this] { gb::cpu::RET_NC(); };
    instructionTable[0xD1] = [this] { gb::cpu::POP_XX(DE); };
    instructionTable[0xD5] = [this] { gb::cpu::PUSH_XX(DE); };
    instructionTable[0xD6] = [this] { gb::cpu::SUB_X(memory->read(program_counter++)); };
    instructionTable[0xD8] = [this] { gb::cpu::RET_C();};
    instructionTable[0xD9] = [this] { gb::cpu::RET(); IME = 1; };
    instructionTable[0xDE] = [this] { gb::cpu::SBC_D8(); };
    instructionTable[0xDF] = [this] { gb::cpu::RST_XX(0x18); };

    instructionTable[0xE0] = [this] { gb::cpu::LDH_A8_A(); };
    instructionTable[0xE1] = [this] { gb::cpu::POP_XX(HL); };
    instructionTable[0xE2] = [this] { gb::cpu::LD_FFC_A(); };
    instructionTable[0xE5] = [this] { gb::cpu::PUSH_XX(HL); };
    instructionTable[0xE6] = [this] { gb::cpu::AND_N(); };
    instructionTable[0xE9] = [this] { gb::cpu::JP_HL(); };
    instructionTable[0xEA] = [this] { gb::cpu::LD_A16_A(); };
    instructionTable[0xEE] = [this] { gb::cpu::XOR_A_D8(); };
    instructionTable[0xEF] = [this] { gb::cpu::RST_XX(0x28); };

    instructionTable[0xF0] = [this] { gb::cpu::LDH_A_A8(); };
    instructionTable[0xF1] = [this] { gb::cpu::POP_XX(AF); };
    instructionTable[0xF3] = [this] { gb::cpu::DI(); };
    instructionTable[0xF5] = [this] { gb::cpu::PUSH_XX(AF); };
    instructionTable[0xF6] = [this] { gb::cpu::OR_D8(); };
    instructionTable[0xF9] = [this] { gb::cpu::LD_SP_HL(); };
    instructionTable[0xFA] = [this] { gb::cpu::LD_A_NN(); };
    instructionTable[0xFB] = [this] { gb::cpu::EI(); }; 
    instructionTable[0xFE] = [this] { gb::cpu::CP_D8(); }; 
    instructionTable[0xFF] = [this] { gb::cpu::RST_XX(0x38); };
}